#!/bin/bash

if [ $1 == "build" ]; then
  docker compose -f docker-compose.yml build
elif [ $1 == "upbuild" ]; then
  docker compose -f docker-compose.yml up --build
elif [ $1 == "up" ]; then
  docker compose -f docker-compose.yml up -d
elif [ $1 == "down" ]; then
  docker compose -f docker-compose.yml down
elif [ "$1" == "restart" ]; then
  docker compose -f docker-compose.yml restart
elif [ "$1" == "restart-hard" ]; then
  docker compose -f docker-compose.yml down
  docker compose -f docker-compose.yml up -d
elif [ "$1" == "reset" ]; then
  docker compose -f docker-compose.yml down
  docker compose -f docker-compose.yml build
  docker compose -f docker-compose.yml up -d
elif [ $1 == "logs" ]; then
  docker compose -f docker-compose.yml logs -f
elif [ $1 == "migrate" ]; then
  docker compose -f docker-compose.yml exec web python manage.py migrate
elif [ $1 == "makemigrations" ]; then
  docker compose -f docker-compose.yml exec web python manage.py makemigrations
elif [ $1 == "merge" ]; then
  docker compose -f docker-compose.yml exec web python manage.py makemigrations --merge
elif [ $1 == "test" ]; then
  docker compose -f docker-compose.yml exec web python manage.py test
elif [ $1 == "pytest" ]; then
  docker compose -f docker-compose.yml exec web pytest
elif [ $1 == "makemessages" ]; then
  docker compose -f docker-compose.yml exec web python manage.py makemessages
elif [ $1 == "compilemessages" ]; then
  docker compose -f docker-compose.yml exec web python manage.py compilemessages
elif [ $1 == "createsuperuser" ]; then
  docker compose -f docker-compose.yml exec web python manage.py createsuperuser
elif [ $1 == "collectstatic" ]; then
  docker compose -f docker-compose.yml exec web python manage.py collectstatic
elif [ $1 == "seed" ]; then
  docker compose -f docker-compose.yml exec web python manage.py seeder
fi
