# Generated by Django 5.1.4 on 2025-01-01 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='End time')),
                ('cost', models.IntegerField(default=0, verbose_name='Cost')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_ongoing', models.BooleanField(default=False, verbose_name='Is ongoing')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Olympiad',
                'verbose_name_plural': 'Olympiads',
            },
        ),
    ]
