# Generated by Django 5.1.4 on 2025-01-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='end_time',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
